# Generated by Django 4.2.3 on 2024-05-21 16:12

from django.db import migrations, models
import news.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        validators=[news.validators.validate_category_length],
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=200,
                        validators=[news.validators.validate_category_length],
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=200,
                        validators=[news.validators.validate_category_length],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        max_length=200,
                        validators=[news.validators.validate_category_length],
                    ),
                ),
            ],
        ),
    ]
